version: '3.8'

services:
  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
      - VITE_AI_SERVICE_URL=http://localhost:5001
      - VITE_SOCKET_URL=http://localhost:5000
    depends_on:
      - backend
      - ai-service
    networks:
      - roam-network

  # Backend (Node.js + Express + Socket.io)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - AI_SERVICE_URL=http://localhost:5001
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - AI_API_KEY=${AI_API_KEY}
    volumes:
      - ./backend/public:/app/public
      - ./logs:/app/logs
    networks:
      - roam-network

  # AI Service (OpenAI + Game Generation)
  ai-service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - roam-network

  # Redis (for session storage and caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - roam-network

  # PostgreSQL (for game data and analytics)
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=roam_game_db
      - POSTGRES_USER=roam_user
      - POSTGRES_PASSWORD=roam_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - roam-network

networks:
  roam-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data: